name: Run_CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: "Run test"
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          $shfile = "/uup_file/uup_download_windows.cmd"
          .\$shfile
