name: Run_CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    name: "Run test"
    runs-on: ubuntu-laster
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: |
          powershell.exe ${{ github.workspace }}/uup_download_windows.cmd
